### ISSUE TITLE
Button-card - black text on an off light

### ISSUE THREAD

**Issue by kzim200** [asierralozano/homeapp-templates#1]
Hello and thank you for this work.  It is exactly what I am was looking for, and I can not wait to see how it develops

Following your example ui-lovelace.yaml file, I created a button for a door when it is off/open then the background is black, and the text stays black.  In your screenshot, the Grande, Pequena, and Dormitorio lights are off with a black background and white text. 
if you are interested here is my yaml snippet
    - type: horizontal-stack
      cards:
      - type: 'custom:button-card'
        entity: binary_sensor.front_door 
        template: binary_sensor   
        name: Front Door  
      - type: 'custom:button-card'
        entity: binary_sensor.kitche_window 
        template: binary_sensor   
        name: Kitchen Window
        icon: mdi:window-closed
      - type: 'custom:button-card'
        entity: binary_sensor.front_door 
        template: light_slim_tile   
        name: Front Door 
![home-display](https://user-images.githubusercontent.com/20750976/86537975-41e3cd00-bef3-11ea-9cba-c8ce9449f871.png)

**Comment by asierralozano** [comment]
Hello!
I've just forgot to mention on the README.md that I'm using the [Google Dark](https://github.com/JuanMTech/google_dark_theme). With that theme, it will work as mine.  You can install it through HACS

I'm working on a more accurate version of my templates, not depending on the installed theme.

BTW, i don't recommend you using the `light_slim_tile` within an horizontal stack. Use it as a individual element, it will looks much better in my opinion.

**Comment by kzim200** [comment]
Thank you.
I switched to Google Dark for now (not my favorite theme, but it fixed the problem).
_"BTW, i don't recommend you using the light_slim_tile within an horizontal stack. Use it as a individual element, it will looks much better in my opinion."_
Unfortunately I am working on a tablet display so space is a premium.  if you have display suggestion for something simular, I would like to hear it.
Is there a list of the templates and cards?

**Comment by asierralozano** [comment]
I'm building some docs that include examples for each card + an screen capture of how they looks.
I'll ping you once I push it :)
